In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%reload_ext autoreload
%autoreload 2

In [3]:
import jax.numpy as jnp
import jax
key = jax.random.key(0)
logits = jax.random.normal(key, (3,10))
top_logits, top_indices = jax.lax.top_k(logits, 4)
top_logits.shape
top_indices.shape

(3, 4)

(3, 4)

In [27]:
key, subkey = jax.random.split(key)
token_idx = jax.random.categorical(subkey, top_logits, axis=-1)
token_idx.shape

(3,)

In [31]:
token_idx
token_idx[:, None]
top_indices
jnp.take_along_axis(top_indices, token_idx[:, None], axis=-1)
next_token = jnp.take_along_axis(top_indices, token_idx[:, None], axis=-1).squeeze(-1)
next_token.shape

Array([1, 1, 3], dtype=int32)

Array([[1],
       [1],
       [3]], dtype=int32)

Array([[3, 4, 7, 1],
       [7, 2, 4, 3],
       [2, 1, 7, 8]], dtype=int32)

Array([[4],
       [2],
       [8]], dtype=int32)

(3,)

In [33]:
next_token[:, None]
jnp.vstack(next_token)

Array([[4],
       [2],
       [8]], dtype=int32)

Array([[4],
       [2],
       [8]], dtype=int32)

# Multiple prompts

In [4]:
key = jax.random.key(0)
logits = jax.random.normal(key, (2,3,4))
logits[:, -1, :].shape

(2, 4)

In [12]:
logits.shape
jnp.array([1,0])[:, None, None].shape
jnp.take_along_axis(logits, jnp.array([1,0])[:, None, None], axis=1).shape

(2, 3, 4)

(2, 1, 1)

(2, 1, 4)

In [11]:
logits
jnp.take_along_axis(logits, jnp.array([1,0])[:, None, None], axis=1).squeeze(1)
jnp.take_along_axis(logits, jnp.array([1,0])[:, None, None], axis=1).squeeze(1).shape

Array([[[ 0.36753944, -0.9082042 , -2.0064416 ,  0.16056262],
        [ 0.13233443, -1.305435  , -0.4055677 , -1.7935358 ],
        [-1.3566552 ,  0.80958456, -0.37977964,  0.08442838]],

       [[-1.895686  , -0.20993415,  0.20252009,  1.3713387 ],
        [-0.60032403, -1.0367845 ,  1.5410699 ,  0.05245331],
        [ 0.03026433,  1.3176132 ,  0.61566246,  1.698919  ]]],      dtype=float32)

Array([[ 0.13233443, -1.305435  , -0.4055677 , -1.7935358 ],
       [-1.895686  , -0.20993415,  0.20252009,  1.3713387 ]],      dtype=float32)

(2, 4)

In [22]:
jnp.zeros((2,3)).at[jnp.array([0,1]), jnp.array([2,0])].set(1)

Array([[0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [24]:
jnp.eye(3)[jnp.array([2,0])]

Array([[0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [29]:
tokens = jnp.ones((2,3))
jnp.place(tokens, jnp.eye(3)[jnp.array([2,0])], jnp.array([4,8]), inplace=False)

Array([[1., 1., 4.],
       [8., 1., 1.]], dtype=float32)

In [28]:
jnp.zeros((2))[:, None]

Array([[0.],
       [0.]], dtype=float32)

In [8]:
import tiktoken
enc = tiktoken.get_encoding("gpt2")
enc.decode([0])
enc.decode(range(0, 21))

'!'

'!"#$%&\'()*+,-./012345'

In [19]:
from generate import prepare_tokens
import tiktoken
enc = tiktoken.get_encoding('gpt2')
prompts = [
    "Capital of India is",
    "I am a teacher, I"
]
prepared = prepare_tokens(prompts)
prepared.shape
# enc.encode(prompts[0])

(2, 6)

In [25]:
jnp.array([1,2,3]) - 1

Array([0, 1, 2], dtype=int32)